const SHOP_DATA = [
  {
    id: 1,
    name: "Cauliflower",
    image: "/images/Cauliflower.png",
    price: 20,
    category: "veg",
  },
  {
    id: 2,
    name: "Bay-Leaves",
    image: "/images/Bay-leaves.png",
    price: 20,
    category: "veg",
  },
  {
    id: 3,
    name: "Carrots",
    image: "/images/Carrots.png",
    price: 20,
    category: "veg",
  },
  {
    id: 4,
    name: "Chilli",
    image: "/images/Chilli.png",
    price: 20,
    category: "veg",
  },
  {
    id: 5,
    name: "Coconut",
    image: "/images/Coconut.png",
    price: 20,
    category: "fruit",
  },
  {
    id: 6,
    name: "Garlic",
    image: "/images/Garlic.png",
    price: 20,
    category: "veg",
  },
  {
    id: 7,
    name: "Ginger",
    image: "/images/Ginger.png",
    price: 20,
    category: "veg",
  },
  {
    id: 8,
    name: "Onion",
    image: "/images/Onion.png",
    price: 20,
    category: "veg",
  },
  {
    id: 9,
    name: "Pineapple",
    image: "/images/Pineapple.png",
    price: 20,
    category: "fruit",
  },
  {
    id: 10,
    name: "Potato",
    image: "/images/Potato.png",
    category: "veg",
    price: 20,
  },
  {
    id: 11,
    name: "Cabbage",
    image: "/images/Purple-Cabbage.png",
    price: 20,
    category: "veg",
  },
  {
    id: 12,
    name: "Tomato",
    image: "/images/Tomato-1.png",
    price: 20,
    category: "fruit",
  },
];

export default SHOP_DATA;
